### ISSUE TITLE
How to insert a page break?

### ISSUE THREAD

**Issue by realtebo** [carlos-meneses/laravel-mpdf#10]
Hi ! Thanks for your package.

Could you document how to add a pagebreak? I can't get it work.

I tried using `<pagebreak />`  in my view  (see [mPDF Doc](https://mpdf.github.io/reference/html-control-tags/pagebreak.html) but it seems simply ignored

Also `<formfeed />`  ( [see](https://mpdf.github.io/reference/html-control-tags/formfeed.html) ) is ignored.

**Comment by carlos-meneses** [comment]
Hello, here a example:

pagebreak-laravel-mpdf-example/resources/views/pdf/document.blade.php in 

https://github.com/carlos-meneses/pagebreak-laravel-mpdf-example/blob/master/resources/views/pdf/document.blade.php

To clone project for test.
