### ISSUE TITLE
função asset('path_to_imagem.png') não funciona para buscar imagem

### ISSUE THREAD

**Issue by mastertag** [carlos-meneses/laravel-mpdf#12]
O documento PDF nunca carrega se você o helper asset() do laravel para carregar uma imagem da sua pasta public no mPDF.

**Comment by carlos-meneses** [comment]
The asset () method returns the url, not the directory path.

For example: In the controller
```php
public function imgUrl () {
    return asset ('images / 01.jpg');
}
```
This will return: `http://127.0.0.1:8000/images/01.jpg`

Instead, if you use:
```php
public function imgUrl () {
    return public_path ('images / 01.jpg');
}
```
This will return: `/home/user/projects/my-project/public/images/01.jpg`
