### ISSUE TITLE
Header Footer Not Showing

### ISSUE THREAD

**Issue by TNP2019** [carlos-meneses/laravel-mpdf#16]
I need header and footer in my pdf.
Tried using instructions provided in laravel-mpdf but it is not showing in pdf
Header is written in following way 
<htmlpageheader name="html_pageheader" style="display:none">
	<table class="body-wrap1" bgcolor="#f6f6f6">
  <tr>
    <td></td>
    
    <td >

      

      <div class="container">

      <table>
        <tr>
          <td>
           <img src="http://localhost/laravel-auth/public/assets/images/archer-interiors-logo.png">
          </td>
        </tr>
		<tr>
          <td align="center"><strong>ORDER FORM</strong></td>
        </tr>
      </table>
      </div>
      
      
    </td>
    <td></td>
  </tr>
</table>
</htmlpageheader>

**Comment by carlos-meneses** [comment]
You must use these tags:

```html
<htmlpageheader name="page-header">
	Your Header Content
</htmlpageheader>

<htmlpagefooter name="page-footer">
	Your Footer Content
</htmlpagefooter>
```

And 
```css
@page {
	header: page-header;
	footer: page-footer;
}
```
https://github.com/carlos-meneses/laravel-mpdf#headers-and-footers

**Comment by Poupoudoum** [comment]
I had everything OK but still no header/footers because of an encoding error in my CSS : 
I had this style :
    .btn[title="Déscendre cette zone"] {
      visibility: hidden;
    }
changed to this :
    .btn[title*="scendre"] {
      visibility: hidden;
    }

And my headers/footers came back... No errors what so ever in log or debug mode ...
