### ISSUE TITLE
Update package to require Mpdf ^8.0

### ISSUE THREAD

**Issue by hoofdletterj** [carlos-meneses/laravel-mpdf#18]
Mpdf has released v8 in march with some bugfixes and features, and most importantly dependency of the FPDI library to version 2. 

Your package blocks upgrading to a higher version than Mpdf v7.1.9 and fpdi v1.6.2 which I would really enjoy to fix some Mpdf issues.

Could you upgrade the dependancies please? I could do it with a PR but there's no tests defined here so I'm a bit hesitant in relation to breaking changes. Thanks!

**Comment by carlos-meneses** [comment]
Thank you for notifying me, I will update it

**Comment by carlos-meneses** [comment]
Package Updated

```
"require": {
	carlos-meneses/laravel-mpdf: "2.1.2"
}
```
