### ISSUE TITLE
Landscape Orientation is Not working. 

### ISSUE THREAD

**Issue by Khurramxhahzad** [carlos-meneses/laravel-mpdf#3]
I am trying to get PDF in landscape orientation but it's not working. I have tried with this method.
$config = [
'orientation'          => 'L'
]
$pdf = PDF::loadView($view, $data, [ ], $config);
return $pdf->stream('Report.pdf');

I have tried both 'P' and 'L' but it is giving PDF only in Portrait mode.

**Comment by carlos-meneses** [comment]
Hello, apparently, it's a bug from the MPDF library. I could solve it using the format option of the configuration; as follows:

`
$config = [
    'format' => 'A4-L' // Landscape
]
$pdf = PDF::loadView($view, $data, [ ], $config);
return $pdf->stream('Report.pdf');
`

**Comment by Khurramxhahzad** [comment]
Thanks !!
