### ISSUE TITLE
The each() function is deprecated. This message will be suppressed on further calls

### ISSUE THREAD

**Issue by imtarundhiman** [carlos-meneses/laravel-mpdf#4]
I am using php 7.2.2 and getting this error. each() is deprecated in php 7.2.

**Comment by imtarundhiman** [comment]
I have resolved the issue. please use 

In mpdf.php (line 10895)

use 

foreach($this->images as $file => $info){}

instead of

while (list($file, $info) = each($this->images)) {}

And in line 13043

use 

foreach($this->formobjects as $file => $info){}

instead of

while (list($file, $info) = each($this->formobjects)) {}

**Comment by seosbg** [comment]
Perfect! Thank you Imtarundhiman.

**Comment by adienurzaman** [comment]
thanks, very working

**Comment by amenavadei** [comment]
Thanks it works for me..
