### ISSUE TITLE
unsupported operand type (+) in LaravelMpdf.php

### ISSUE THREAD

**Issue by timmy1420** [carlos-meneses/laravel-mpdf#6]
'fontdata' => $fontData + $this->getConfig('custom_font_data'),

could be changed to

'fontdata' => $fontData,

![type](https://user-images.githubusercontent.com/13759959/49915101-b4eda480-fe72-11e8-8c7e-6e23dc266b05.png)

**Comment by alaamebrahim** [comment]
Do this part of documentation 
https://github.com/carlos-meneses/laravel-mpdf/blob/master/readme.md#config

**Comment by carlos-meneses** [comment]
You must configure an empty array `'custom_font_data' => []` inside your `config/pdf.php` file, as indicated @alaamebrahim and documentation:
https://github.com/carlos-meneses/laravel-mpdf/blob/master/readme.md#config

**Comment by realtebo** [comment]
My  config.php is this

```
return [
	'mode'                 => '',
	'format'               => 'A4',
	'default_font_size'    => '12',
	'default_font'         => 'sans-serif',
	'margin_left'          => 10,
	'margin_right'         => 10,
	'margin_top'           => 10,
	'margin_bottom'        => 10,
	'margin_header'        => 0,
	'margin_footer'        => 0,
	'orientation'          => 'P',
	'title'                => 'Laravel mPDF',
	'author'               => '',
	'watermark'            => '',
	'show_watermark'       => false,
	'watermark_font'       => 'sans-serif',
	'display_mode'         => 'fullpage',
	'watermark_text_alpha' => 0.1,
	'custom_font_dir'      => '',
	'custom_font_data' 	   => [],
];
```

I did config:cache

But running I got the error

```
Unsupported operand types
```

In the following row `/vendor/carlos-meneses/laravel-mpdf/src/LaravelMpdf/LaravelMpdf.php` at the line
```
            'fontdata' => $fontData + $this->getConfig('custom_font_data'),
```
